-- ALTER TABLE startups
--     ADD COLUMN IF NOT EXISTS revenue NUMERIC(12,2) DEFAULT 0.00,
--     ADD COLUMN IF NOT EXISTS profit NUMERIC(12,2) DEFAULT 0.00,
--     ADD COLUMN IF NOT EXISTS priority SMALLINT NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS intrested_buyers INT NOT NULL DEFAULT 0;

-- ALTER TABLE assets
--     ADD COLUMN IF NOT EXISTS priority SMALLINT NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS interested_buyers INT NOT NULL DEFAULT 0;
    